import type {
  ActivityEntry,
  BuildSiteState,
  CrewMember,
  Equipment,
  ModuleState,
  MoonbaseState,
  WorkOrder,
} from './types'
import { createStarterConstruction } from './constructionCatalog'

export const MOONBASE_SEED = 240826

export const INITIAL_BUILD_SITES: BuildSiteState[] = [
  {
    id: 'site-power-west',
    label: 'West Ridge',
    x: 2,
    y: 1,
    width: 5,
    height: 4,
    kind: 'exterior_power',
    connectionSide: null,
    occupiedBy: null,
  },
  {
    id: 'site-power-east',
    label: 'East Ridge',
    x: 19,
    y: 2,
    width: 5,
    height: 4,
    kind: 'exterior_power',
    connectionSide: null,
    occupiedBy: null,
  },
  {
    id: 'site-power-south',
    label: 'South Shelf',
    x: 2,
    y: 14,
    width: 5,
    height: 4,
    kind: 'exterior_power',
    connectionSide: null,
    occupiedBy: null,
  },
  {
    id: 'site-bay-northwest',
    label: 'Northwest Bay',
    x: 8,
    y: 3,
    width: 5,
    height: 6,
    kind: 'pressurized_bay',
    connectionSide: 'south',
    occupiedBy: null,
  },
  {
    id: 'site-bay-northeast',
    label: 'Northeast Bay',
    x: 14,
    y: 3,
    width: 5,
    height: 6,
    kind: 'pressurized_bay',
    connectionSide: 'south',
    occupiedBy: null,
  },
  {
    id: 'site-bay-southwest',
    label: 'Southwest Bay',
    x: 8,
    y: 10,
    width: 5,
    height: 6,
    kind: 'pressurized_bay',
    connectionSide: 'north',
    occupiedBy: null,
  },
  {
    id: 'site-bay-southeast',
    label: 'Padside Bay',
    x: 14,
    y: 10,
    width: 5,
    height: 6,
    kind: 'pressurized_bay',
    connectionSide: 'north',
    occupiedBy: null,
  },
]

const modules: ModuleState[] = [
  {
    id: 'module-habitat',
    name: 'Habitat Aster',
    type: 'habitat',
    location: 'habitat',
    position: { x: 1, y: 6, width: 6, height: 7 },
    atmosphere: 'yes',
    condition: 91,
    powerPriority: 1,
    breached: false,
  },
  {
    id: 'module-corridor',
    name: 'Central Spine',
    type: 'corridor',
    location: 'corridor',
    position: { x: 6, y: 8, width: 14, height: 3 },
    atmosphere: 'yes',
    condition: 94,
    powerPriority: 2,
    breached: false,
  },
  {
    id: 'module-life-support',
    name: 'Life Support',
    type: 'life_support',
    location: 'life-support',
    position: { x: 8, y: 3, width: 5, height: 6 },
    atmosphere: 'yes',
    condition: 87,
    powerPriority: 1,
    breached: false,
  },
  {
    id: 'module-storage',
    name: 'Stores',
    type: 'storage',
    location: 'storage',
    position: { x: 8, y: 10, width: 5, height: 6 },
    atmosphere: 'yes',
    condition: 89,
    powerPriority: 3,
    breached: false,
  },
  {
    id: 'module-laboratory',
    name: 'Kepler Laboratory',
    type: 'laboratory',
    location: 'laboratory',
    position: { x: 14, y: 3, width: 5, height: 6 },
    atmosphere: 'no',
    condition: 58,
    powerPriority: 2,
    breached: true,
  },
  {
    id: 'module-airlock',
    name: 'South Airlock',
    type: 'airlock',
    location: 'airlock',
    position: { x: 14, y: 10, width: 5, height: 6 },
    atmosphere: 'yes',
    condition: 96,
    powerPriority: 1,
    breached: false,
  },
  {
    id: 'module-solar-skid',
    name: 'Solar / Battery Skid',
    type: 'solar_battery_skid',
    location: 'solar-skid',
    position: { x: 19, y: 2, width: 5, height: 4 },
    atmosphere: 'no',
    condition: 82,
    powerPriority: 1,
    breached: false,
  },
  {
    id: 'module-landing-pad',
    name: 'Shackleton Pad',
    type: 'landing_pad',
    location: 'landing-pad',
    position: { x: 19, y: 11, width: 5, height: 6 },
    atmosphere: 'no',
    condition: 93,
    powerPriority: 3,
    breached: false,
  },
]

const crew: CrewMember[] = [
  {
    id: 'crew-amina-okafor',
    name: 'Amina Okafor',
    role: 'Mission Commander',
    trait: 'Calm under cascading alerts',
    status: 'idle',
    health: 96,
    fatigue: 24,
    morale: 88,
    location: 'habitat',
    taskId: null,
    skills: { engineering: 5, science: 4, medicine: 3, operations: 9 },
  },
  {
    id: 'crew-mateo-alvarez',
    name: 'Mateo Alvarez',
    role: 'Structural Engineer',
    trait: 'Methodical seal inspector',
    status: 'idle',
    health: 94,
    fatigue: 31,
    morale: 82,
    location: 'airlock',
    taskId: null,
    skills: { engineering: 9, science: 3, medicine: 2, operations: 6 },
  },
  {
    id: 'crew-soo-jin-park',
    name: 'Soo-jin Park',
    role: 'Life-support Engineer',
    trait: 'Protects reserve margins',
    status: 'idle',
    health: 92,
    fatigue: 27,
    morale: 85,
    location: 'life-support',
    taskId: null,
    skills: { engineering: 8, science: 5, medicine: 4, operations: 7 },
  },
  {
    id: 'crew-leila-haddad',
    name: 'Leila Haddad',
    role: 'Materials Scientist',
    trait: 'Careful experimentalist',
    status: 'idle',
    health: 91,
    fatigue: 20,
    morale: 90,
    location: 'habitat',
    taskId: null,
    skills: { engineering: 4, science: 10, medicine: 3, operations: 5 },
  },
  {
    id: 'crew-jonah-reed',
    name: 'Jonah Reed',
    role: 'Flight Medic',
    trait: 'Refuses unsafe exposure',
    status: 'idle',
    health: 97,
    fatigue: 18,
    morale: 84,
    location: 'habitat',
    taskId: null,
    skills: { engineering: 2, science: 5, medicine: 10, operations: 5 },
  },
  {
    id: 'crew-nia-kimani',
    name: 'Nia Kimani',
    role: 'Surface Operations Specialist',
    trait: 'Fast equipment retrieval',
    status: 'idle',
    health: 95,
    fatigue: 29,
    morale: 86,
    location: 'storage',
    taskId: null,
    skills: { engineering: 6, science: 3, medicine: 3, operations: 9 },
  },
]

const equipment: Equipment[] = [
  {
    id: 'equipment-eva-01',
    name: 'EVA Suit 01',
    type: 'eva_suit',
    status: 'available',
    location: 'airlock',
    condition: 94,
    reservedForWorkOrderId: null,
    assignedCrewId: null,
  },
  {
    id: 'equipment-eva-02',
    name: 'EVA Suit 02',
    type: 'eva_suit',
    status: 'available',
    location: 'storage',
    condition: 86,
    reservedForWorkOrderId: null,
    assignedCrewId: null,
  },
  {
    id: 'equipment-engineering-01',
    name: 'Engineering Kit 01',
    type: 'engineering_kit',
    status: 'available',
    location: 'storage',
    condition: 88,
    reservedForWorkOrderId: null,
    assignedCrewId: null,
  },
  {
    id: 'equipment-engineering-02',
    name: 'Engineering Kit 02',
    type: 'engineering_kit',
    status: 'available',
    location: 'life-support',
    condition: 96,
    reservedForWorkOrderId: null,
    assignedCrewId: null,
  },
  {
    id: 'equipment-medical-01',
    name: 'Medical Kit 01',
    type: 'medical_kit',
    status: 'available',
    location: 'habitat',
    condition: 92,
    reservedForWorkOrderId: null,
    assignedCrewId: null,
  },
  {
    id: 'equipment-rover-01',
    name: 'Utility Rover Kestrel',
    type: 'rover',
    status: 'available',
    location: 'airlock',
    condition: 84,
    reservedForWorkOrderId: null,
    assignedCrewId: null,
  },
]

const workOrders: WorkOrder[] = [
  {
    id: 'work-seal-lab',
    type: 'seal_breach',
    label: 'Seal laboratory breach',
    detail: 'Retrieve an EVA suit and engineering kit, cross the isolated zone, and patch the micrometeorite puncture.',
    location: 'laboratory',
    status: 'ready',
    priority: 5,
    requiredSkill: 'engineering',
    minimumSkill: 7,
    requiredEquipment: ['eva_suit', 'engineering_kit'],
    hazard: 'vacuum',
    prerequisiteIds: [],
    assignedCrewIds: [],
    reservedEquipmentIds: [],
    progressHours: 0,
    durationHours: 2,
    logisticsHoursRemaining: 0,
    startedAtHour: null,
    completedAtHour: null,
  },
  {
    id: 'work-repressurize-lab',
    type: 'repressurize_lab',
    label: 'Repressurize laboratory',
    detail: 'Pressure-test the repair and restore the zone from vacuum through low pressure to a safe atmosphere.',
    location: 'laboratory',
    status: 'blocked',
    priority: 5,
    requiredSkill: 'engineering',
    minimumSkill: 6,
    requiredEquipment: ['engineering_kit'],
    hazard: 'indoor',
    prerequisiteIds: ['work-seal-lab'],
    assignedCrewIds: [],
    reservedEquipmentIds: [],
    progressHours: 0,
    durationHours: 2,
    logisticsHoursRemaining: 0,
    startedAtHour: null,
    completedAtHour: null,
  },
  {
    id: 'work-research-sintering',
    type: 'research',
    label: 'Research Regolith Sintering',
    detail: 'Qualify microwave sintering parameters for local anorthite-rich regolith after the laboratory is restored.',
    location: 'laboratory',
    status: 'blocked',
    priority: 4,
    requiredSkill: 'science',
    minimumSkill: 7,
    requiredEquipment: [],
    hazard: 'indoor',
    prerequisiteIds: ['work-repressurize-lab'],
    assignedCrewIds: [],
    reservedEquipmentIds: [],
    progressHours: 0,
    durationHours: 3,
    logisticsHoursRemaining: 0,
    startedAtHour: null,
    completedAtHour: null,
  },
  {
    id: 'work-clean-solar',
    type: 'clean_solar',
    label: 'Clean priority solar bank',
    detail: 'Use the rover before the dust front peaks to keep the battery from becoming the research bottleneck.',
    location: 'solar-skid',
    status: 'ready',
    priority: 4,
    requiredSkill: 'operations',
    minimumSkill: 6,
    requiredEquipment: ['eva_suit', 'rover'],
    hazard: 'eva',
    prerequisiteIds: [],
    assignedCrewIds: [],
    reservedEquipmentIds: [],
    progressHours: 0,
    durationHours: 2,
    logisticsHoursRemaining: 0,
    startedAtHour: null,
    completedAtHour: null,
  },
]

const initialEvents = (): ActivityEntry[] => [
  {
    id: 'event-0003',
    elapsedHours: 0,
    missionDay: 1,
    hour: 6,
    worldRevision: 1,
    planRevision: 1,
    phase: 'observed',
    actor: 'system',
    message: 'Dust front ETA 3 hours; projected solar output will fall below live demand.',
    targetIds: ['module-solar-skid'],
  },
  {
    id: 'event-0002',
    elapsedHours: 0,
    missionDay: 1,
    hour: 6,
    worldRevision: 1,
    planRevision: 1,
    phase: 'observed',
    actor: 'system',
    message: 'Kepler Laboratory is isolated at vacuum after a micrometeorite puncture.',
    targetIds: ['module-laboratory', 'work-seal-lab'],
  },
  {
    id: 'event-0001',
    elapsedHours: 0,
    missionDay: 1,
    hour: 6,
    worldRevision: 1,
    planRevision: 1,
    phase: 'system',
    actor: 'system',
    message: 'First-shift handover complete. Six crew await a bounded response plan.',
    targetIds: [],
  },
]

export const createInitialState = (): MoonbaseState => ({
  baseName: 'Shackleton Relay',
  seed: MOONBASE_SEED,
  missionDay: 1,
  hour: 6,
  elapsedHours: 0,
  worldRevision: 1,
  scenarioStatus: 'active',
  map: { width: 24, height: 18 },
  settlement: {
    phase: 'landing',
    layout: createStarterConstruction(),
    buildSites: structuredClone(INITIAL_BUILD_SITES),
    builtModuleIds: ['module-habitat', 'module-corridor', 'module-landing-pad'],
  },
  objective: {
    id: 'restore_lab_and_research_sintering',
    summary: 'Restore Kepler Laboratory and complete Regolith Sintering research without crossing the declared oxygen floor.',
    successCriteria: [
      'Laboratory breach sealed and atmosphere restored to Yes.',
      'Regolith Sintering research complete.',
      'Observed oxygen reserve never falls below the plan floor.',
    ],
    recommendedOxygenFloorHours: 12,
  },
  reserves: {
    oxygenHours: 32,
    minimumOxygenHours: 32,
    waterDays: 9.4,
    foodDays: 8.7,
    constructionStock: 14,
  },
  power: {
    solarGenerationKw: 24,
    demandKw: 18,
    batteryKwh: 30,
    batteryCapacityKwh: 40,
    dustDeratePercent: 0,
    status: 'surplus',
  },
  lab: {
    moduleId: 'module-laboratory',
    atmosphere: 'no',
    breached: true,
    sealed: false,
  },
  dust: {
    startsAtHour: 3,
    active: false,
    severity: 'moderate',
    baseDeratePercent: 50,
    mitigatedDeratePercent: 15,
    mitigated: false,
  },
  modules: structuredClone(modules),
  crew: structuredClone(crew),
  equipment: structuredClone(equipment),
  workOrders: structuredClone(workOrders),
  research: {
    id: 'research-regolith-sintering',
    title: 'Regolith Sintering',
    status: 'blocked',
    progressHours: 0,
    requiredHours: 3,
    assignedResearcherId: null,
    unlocks: [],
  },
  alerts: [
    {
      id: 'alert-lab-breach',
      severity: 'critical',
      title: 'Laboratory pressure: No',
      detail: 'The isolated lab cannot support research until the puncture is sealed and the zone is repressurized.',
    },
    {
      id: 'alert-dust-forecast',
      severity: 'warning',
      title: 'Dust front in 3 hours',
      detail: 'Unmitigated solar output will fall to 12 kW against 18 kW base demand.',
    },
  ],
  events: initialEvents(),
  learning: {
    currentPhase: 'ground',
    completedLoops: 0,
    achieved: { ground: false, plan: false, supervise: false, verify: false },
    coaching: 'Ground the response in live pressure, oxygen, power, crew, equipment, and work-order evidence.',
    evidence: [],
  },
  operationsPlan: {
    id: 'operations-plan-001',
    title: 'Laboratory recovery',
    status: 'draft',
    revision: 1,
    basedOnWorldRevision: 1,
    objective: null,
    constraints: { oxygenFloorHours: 12, protectedCrewIds: [] },
    horizonHours: 12,
    stopCondition: null,
    actions: [],
    committedAtHour: null,
    baseline: null,
  },
  lastAdvance: null,
  verification: null,
})
